# Generated by Django 5.1.2 on 2024-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='divar_on_message_setup',
            field=models.BooleanField(default=False),
        ),
    ]
