# Generated by Django 5.1.2 on 2024-10-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postdetail_divar_on_message_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_id',
        ),
    ]
