# Generated by Django 5.1.2 on 2024-10-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_conversation_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('POST_CONVERSATION_RESPOND_PROMPT', 'POST_CONVERSATION_RESPOND_PROMPT'), ('POST_CONVERSATION_STATUS_PROMPT', 'POST_CONVERSATION_STATUS_PROMPT')], max_length=1024, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
