# Generated by Django 5.1.2 on 2024-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCompletionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
