# Generated by Django 5.1.2 on 2024-10-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_postdetail_divar_post_return_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
